### ISSUE TITLE
math content does not recognize align

### ISSUE THREAD

**Issue by xinist** [gillescastel/latex-snippets#10]
Hi,

This repo is extremely useful for me. Everything works fine in most math environments, but not for the align (and align*) environment. I did some google and found that "AmsA" seems to represent align. But it is already in the file...

Thank you!

Best

**Comment by Konfekt** [comment]
This should be fine with the latest version 2.1 of vimtex and #14

**Comment by Konfekt** [comment]
If you want to keep using the built-in TeX syntax highlighting, then you need to add`amsmath.vim` from Charles E. Campbell at http://www.drchip.org/astronaut/vim/vbafiles/amsmath.vba.gz to the `after/syntax/` folder. 
This file adds highlighting for the align environments by

```vim
  call TexNewMathZone("E","align",1)
  call TexNewMathZone("F","alignat",1)
  call TexNewMathZone("G","equation",1)
  call TexNewMathZone("H","flalign",1)
  call TexNewMathZone("I","gather",1)
  call TexNewMathZone("J","multline",1)
  call TexNewMathZone("K","xalignat",1)
  call TexNewMathZone("L","xxalignat",0)
```

**Comment by gillescastel** [comment]
This should be fixed now. Update vimtex and use the following code: 

https://github.com/gillescastel/latex-snippets/blob/baa1b42ed9558b4a7ba220c50c5046957719f898/tex.snippets#L1-L12
