### ISSUE TITLE
VimTeX 2.0 - Math contex seems to be broke

### ISSUE THREAD

**Issue by Hello-Helo** [gillescastel/latex-snippets#13]
Helo everyone, i updated VimTeX and every math contex snnippet stopped working, mabybe something in the definition broke. I am busy with uni now and will only be able to fix them in the winter break. I removed the 'context "math()"' and I will need to manually expand them if there  conflicts with my language (like sr). Dont recomment updating if you use the snippets daily.

**Comment by antotocar34** [comment]
See pull request #12. Worked for me.

**Comment by danielfalbo** [comment]
New update: https://github.com/lervag/vimtex/issues/1864#issuecomment-739916236.

**Comment by rednaz1337** [comment]
I'm running the newest vimtex version and still have this problem.

Edit: the \[ \] environments aren't recognised, but $...$ are. Weird

**Comment by Hello-Helo** [comment]
You can just change the math environment definition to the one the the pull request #12, will fix it
