### ISSUE TITLE
Please update the repo

### ISSUE THREAD

**Issue by anstadnik** [gillescastel/latex-snippets#15]
Hi! I can see that you've updated your [post](https://castel.dev/post/lecture-notes-1/) regarding detecting context. However, those changes are not in this repo. I assume that you didn't update it. I find this repo highly inspirational and I use it a lot, so please update it if it's possible. I changed the detection on my side, but I suppose that there might be more useful changes.

**Comment by gillescastel** [comment]
This should be fixed now!
