### ISSUE TITLE
Suggestion: dynamically get tex math zones

### ISSUE THREAD

**Issue by jvdoorn** [gillescastel/latex-snippets#7]
https://github.com/gillescastel/latex-snippets/blob/ce1746d4a7b46e9e6da1a8d473ab24f734b2fa26/tex.snippets#L2

To assure that all math zones are included we can load them from the syntax list as such:
```python
vim.command('redir @a | silent exe "syntax list @texMathZones" | redir END')
texMathZones = [x.strip() for x in vim.eval('@a').split(',')][1:]
```

This will collect all (properly) registered texMathZones and store them in register `a` (by properly registered please refer to https://github.com/vim/vim/blob/1d9215b9aaa120b9d78fee49488556f73007ce78/runtime/syntax/tex.vim#L418-L421). We then split the list and remove any whitespace. The rest of the code can remain unchanged. I think this makes the code more resilient to change and might pick up math zones that are currently missing or added by other syntax files.

**Comment by gillescastel** [comment]
That's very interesting, thanks for sharing! For some reason, I only see this now. The current code doesn't use this long list anymore, so I'm closing this. 

https://github.com/gillescastel/latex-snippets/blob/baa1b42ed9558b4a7ba220c50c5046957719f898/tex.snippets#L1-L12

Once again, thanks for sharing and sorry for answering so late.
