### ISSUE TITLE
latex math packages

### ISSUE THREAD

**Issue by ivannomad** [gillescastel/latex-snippets#9]
Hello! For math I use next `\usepackage{mathtools, amssymb}`. If I type `\mathbb{R}` in .tex file it compile as double-struck R which means real numbers. But in your tex.snippet file you use next code for number sets:
```ultisnips
snippet RR "real" iA
\R
endsnippet
```
I think, that is more convenient than `\mathbb{R}`. But unfortunately, my compiler not recognise `\R` even if I use it in math mode `$\R$`
What math packages do you use for this?

**Comment by NikitaEvs** [comment]
Hello! You can find a definition for `\R` command in his [preamble.tex](https://github.com/gillescastel/university-setup/blob/master/preamble.tex#L35).
`
\newcommand\R{\ensuremath{\mathbb{R}}}
`

**Comment by ivannomad** [comment]
Thanks, it really help me! But I made minor changes. Now my commands look as follow:
```latex
\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\Q}{\mathbb{Q}}
\renewcommand{\O}{\emptyset}
```

**Comment by NikitaEvs** [comment]
You are welcome!

**Comment by gillescastel** [comment]
Great question @ivannomad  and thanks for answering @NikitaEvs!
